export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{width:"100%",height:"20%", color:"gray",border:"2px solid black", padding:"20px"}}>Header</header>

        {children}
        <footer style={{width:"100%",height:"20%", color:"green",border:"2px solid black", padding:"20px"}}>Footer</footer>
        
        
        </body>
    </html>
  )
}
